name: Release FrameScale

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'FrameScale/**'
      - '.github/workflows/release-framescale.yml'

permissions:
  contents: write

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'chore: bump')"
    uses: ./.github/workflows/release-addon.yml
    with:
      addon: FrameScale
      cf_project_id: "1462718"
    secrets:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
