name: Release AutoQueue

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'AutoQueue/**'
      - '.github/workflows/release-autoqueue.yml'

permissions:
  contents: write

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'chore: bump')"
    uses: ./.github/workflows/release-addon.yml
    with:
      addon: AutoQueue
      cf_project_id: "1462604"
    secrets:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
